@startuml basket
left to right direction

class Equipo {
    -String: nombre
    -Jugador jugadores[15]
    -List<Equipo> equiposJugados
    +boolean agregarJugador(Jugador j)
}

abstract class Jugador {
    -String: nombre
    -int: altura
    -int: habilidad
    +anotarPuntos(int puntos)
    +hacerFalta()
}

class Base {
}

class Escolta {
}

class Alero {
}

class AlaPivot {
}

class Pivot {
}

class Partido {
    -int: MAX_PUNTOS: 150
    -int: MIN_PUNTOS: 35
    +calcularResultado(): int
}

class PartidoExibicion {
}

class PartidoOficial {
    +verificarSiYaSeJugó(Equipo rival): boolean
}

class Local {
    // más porcentaje de ganar
}

class Visitante {
    // menos porcentaje de ganar
}

class Arbitro {
    -String: nombre
    -boolean: enfermo
    +estarEnfermo(): boolean
}

interface GestorArchivo {
    +leerEquipos(): List<Equipo>
    +guardarResumen(Equipo equipo, String resumen)
}

class Temporada{

}

class Excepciones{

}

Temporada *-- Partido
Temporada *-- Equipo

Equipo *-- Jugador
Equipo *-- Partido

Jugador <|-- Base
Jugador <|-- Escolta
Jugador <|-- Alero
Jugador <|-- AlaPivot
Jugador <|-- Pivot

Partido *-- Arbitro
Partido <|-- PartidoOficial
Partido <|-- PartidoExibicion

PartidoOficial *-- Local
PartidoOficial *-- Visitante
PartidoOficial -- Equipo : local
PartidoOficial -- Equipo : visitante

GestorArchivo <|.. GestionArchivos

@enduml