@startuml basket
top to bottom direction

package Model{
    class Equipo {
        -String: nombre
        -int: numJugadores
        -Jugador jugadores[15]
        +boolean agregarJugador(Jugador j)
        +boolean eliminarJugador(Jugador j)
    }

    abstract class Jugador {
        -String: nombre
        -int: dorsal
        -int: altura
        -int: habilidad
        -int: puntos
        -int: faltas
        +anotarPuntos(int puntos)
        +hacerFalta()
    }

    class Base {
    }

    class Escolta {
    }

    class Alero {
    }

    class AlaPivot {
    }

    class Pivot {
    }

    class Partido {
        #int: MAX_PUNTOS = 150
        #int: MIN_PUNTOS = 35
        #Arbitro: arbitro
        #int: resultadoLocal
        #int: resultadoVisitante
        #Equipo: ganador
        #Equipo: equipoLocal
        #Equipo: equipoVisitante
        +calcularResultado(): Equipo
    }

    class PartidoExibicion {
    }

    class PartidoOficial {
        +verificarPartido(Equipo rival): boolean
    }

    class Local {
        // más porcentaje de ganar
    }

    class Visitante {
        // menos porcentaje de ganar
    }

    class Arbitro {
        -String: nombre
        -boolean: enfermo
        +estarEnfermo(): boolean
    }

    interface GestorArchivo {
        +leerEquipos(): List<Equipo>
        +leerArbitros(): List<Arbitro>
        +guardarResumen(Equipo equipo, String resumen)
    }

    class Temporada {
        -static Temporada instancia
        +static getInstancia(): Temporada
        +registrarPartidoJugado()
        +jugarPartido(Equipo equipo1, Equipo equipo2, boolean esOficial)
        +mostrarResumenUltimoPartido()
        +mostrarHistoricoTemporada()
        +mostrarResumenJugadoresPorTipo(String tipo)
    }

    class Excepciones{
    }
}

package View{
    class Main{}
}

package Controller{
    class Switch{}
}

Temporada *-- Partido
Temporada *-- Equipo

Equipo *-- Jugador
Equipo *-- Partido

Jugador <|-- Base
Jugador <|-- Escolta
Jugador <|-- Alero
Jugador <|-- AlaPivot
Jugador <|-- Pivot

Partido *-- Arbitro
Partido <|-- PartidoOficial
Partido <|-- PartidoExibicion

PartidoOficial *-- Local
PartidoOficial *-- Visitante
PartidoOficial -- Equipo : local
PartidoOficial -- Equipo : visitante

GestorArchivo <|.. Fichero

View --> Controller
Controller --> Model

@enduml
